---
driver:
  name: vagrant

provisioner:
  name: chef_zero

  attributes:
    authorization:
      sudo:
        users:
          - vagrant
        passwordless: true
        include_sudoers_d: true

platforms:
- name: centos-7
  transport:
    name: speedy_ssh
  driver_config:
    box:     criteo-centos-7.2-core

suites:
<%= require 'erubis'; Erubis::Eruby.new(File.read('.kitchen_suites.yml')).evaluate if File.exists?('.kitchen_suites.yml') %>
